FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=djamel
ENV N8N_BASIC_AUTH_PASSWORD=DreamDubai2024
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=http
ENV WEBHOOK_TUNNEL_URL=https://your-subdomain.up.railway.app
ENV TZ=Asia/Dubai

CMD ["n8n"]